output_dir: "experiments/U-Ones/ensemble"
trained_epochs: 0

data:
    data_dir: "ensemble_data"
    train_file: "ensemble_U_Ones_train_features.csv"
    val_file: "ensemble_U_Ones_valid_features.csv"
    test_file: "ensemble_U_Ones_valid_features.csv"
    batch_size: 64

data_agumentation:
    type: "none"

max_epochs: 50

pca:
    enabled: true
    n_components: "auto"

model:
    type: "models.MLP"
    params:
        num_models: 3
        num_classes: 14
        num_meta_features: 3

optimizer:
    type: "Adam"
    params:
        lr : 0.01
        weight_decay: 1.0e-5

scheduler:
    type: "ReduceLROnPlateau"
    params:
        mode: "min"
        factor: 0.5
        patience: 3
        min_lr: 1.0e-6

earlyStop:
    type: "utils.EarlyStopping"
    params: 
        patience: 5
        min_delta: 0.0

loss:
  type: "losses.CheXpertLoss"
  params:
    policy: "U-Zeros"