output_dir: "experiments/U-Ones/exp2"
trained_epochs: 0
max_epochs: 50

data:
    data_dir: "CheXpert-v1.0-small"
    train_file: "train_balanced.csv"
    val_file: “valid.csv”
    test_file: "valid.csv"
    batch_size: 32

data_agumentation:
    type: "none"

model:
    type: "models.ResNetSE"
    params:
        num_classes: 14


optimizer:
    type: "Adam"
    params:
        lr : 0.01


scheduler:
    type: "ReduceLROnPlateau"
    params:
        mode: "min"
        factor: 0.5
        patience: 5
        min_lr: 1.0e-6

earlyStop:
    type: "utils.EarlyStopping"
    params: 
        patience: 7
        min_delta: 0.0

loss:
  type: "losses.CheXpertLoss"
  params:
    policy: "U-Ones"